name: $(Date:yyyyMMdd)$(Rev:.r)


stages:
- stage: Build&test
  jobs:
  - job: 'Service1'
    steps:
      - checkout: self
      - task: Docker@2
        displayName: docker build
        inputs:
          containerRegistry: 'DockerHub'
          repository: 'r4fi/alletasks'
          command: 'buildAndPush'
          Dockerfile: '**/Rafal.Bochenski.Service1.Dockerfile'
          tags: 's1-$(Build.BuildId)'
      - task: CmdLine@2
        displayName: docker run test
        inputs:
          script: |
            docker run --entrypoint="" r4fi/alletasks:s1-$(Build.BuildId) bash dotnet test